// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFSb4Eo8Vni3SzlSWTcoZIUBR0Hld5MFY',
    appId: '1:345697199213:web:0fdf119cd9e4c67c5bcb64',
    messagingSenderId: '345697199213',
    projectId: 'covoiturage-esmt',
    authDomain: 'covoiturage-esmt.firebaseapp.com',
    databaseURL: 'https://covoiturage-esmt-default-rtdb.firebaseio.com',
    storageBucket: 'covoiturage-esmt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY8bQ45dcqUsH-aVCx7ABCzL-Q2fBLVnw',
    appId: '1:345697199213:android:782905c4d69770245bcb64',
    messagingSenderId: '345697199213',
    projectId: 'covoiturage-esmt',
    databaseURL: 'https://covoiturage-esmt-default-rtdb.firebaseio.com',
    storageBucket: 'covoiturage-esmt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_GoU7eXIgHdS-moZYf1neH4g-HrL98Go',
    appId: '1:345697199213:ios:4576ff8cf05069bb5bcb64',
    messagingSenderId: '345697199213',
    projectId: 'covoiturage-esmt',
    databaseURL: 'https://covoiturage-esmt-default-rtdb.firebaseio.com',
    storageBucket: 'covoiturage-esmt.firebasestorage.app',
    iosBundleId: 'com.example.covoiturageEsmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_GoU7eXIgHdS-moZYf1neH4g-HrL98Go',
    appId: '1:345697199213:ios:4576ff8cf05069bb5bcb64',
    messagingSenderId: '345697199213',
    projectId: 'covoiturage-esmt',
    databaseURL: 'https://covoiturage-esmt-default-rtdb.firebaseio.com',
    storageBucket: 'covoiturage-esmt.firebasestorage.app',
    iosBundleId: 'com.example.covoiturageEsmt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFSb4Eo8Vni3SzlSWTcoZIUBR0Hld5MFY',
    appId: '1:345697199213:web:84cd9e9fc559e5845bcb64',
    messagingSenderId: '345697199213',
    projectId: 'covoiturage-esmt',
    authDomain: 'covoiturage-esmt.firebaseapp.com',
    databaseURL: 'https://covoiturage-esmt-default-rtdb.firebaseio.com',
    storageBucket: 'covoiturage-esmt.firebasestorage.app',
  );
}
